# Use Node.js LTS version
FROM node:22.14.0

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY ./frontend/package.json ./frontend/package-lock.json ./
RUN npm install --production

# Copy the entire project to the container
COPY ./frontend .

# Expose the port
EXPOSE 80

# Start the Express server
CMD ["node", "server.js"]
