on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  unit:
    uses: ./.github/workflows/unit.yml
  build:
    uses: ./.github/workflows/build-docker-image.yml
    needs:
      - unit
    with:
      TOKEN: ${{ secrets.TOKEN }}
  deploy:
    uses: ./.github/workflows/tofu-apply.yml
    needs:
      - build
