name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:


  Deploy-On-AzureWebApps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      
      - name: Unit Test
        run: |
            make venv && make test
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/health_calculator:latest


      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'health-calculator'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE}}
          images: 'ghcr.io/fabienchevalier/health-calculator:latest'
    

    