name: Apply terraform plan

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: write

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Apply tofu plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: tofu apply
        uses: dflook/tofu-apply@v1
        with:
          path: ./terraform